from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.tuning.duel_weight_profiles import WEIGHT_KEYS, load_profile, validate_profiles

SOURCE_PATHS = (
    Path("configs/evaluation_weights/default.json"),
    Path("configs/evaluation_weights/tuned-opponent-pressure.json"),
)
HEADER_PATH = Path("battlesnake/c-core/core/duel_weight_profiles_generated.h")
SOURCE_PATH = Path("battlesnake/c-core/core/duel_weight_profiles_generated.c")
MANIFEST_PATH = Path("configs/evaluation_weights/duel_weight_profiles.sha256")


def _c_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def _c_double(value: float) -> str:
    rendered = repr(value)
    return rendered if "." in rendered or "e" in rendered.lower() else rendered + ".0"


def render_header() -> str:
    sources = ", ".join(str(path) for path in SOURCE_PATHS)
    return f"""/* Generated by tools/tuning/generate_duel_weight_profiles.py.
 * Sources: {sources}
 * DO NOT EDIT. */
#pragma once

#include <stddef.h>

#include "search_stats.h"

typedef struct {{
    int schema_version;
    const char* name;
    const char* version;
    const char* status;
    const char* sha256;
    CoreEvaluationWeights weights;
}} CoreDuelWeightProfile;

size_t CoreDuelWeightProfileCount(void);
const CoreDuelWeightProfile* CoreDuelWeightProfileAt(size_t index);
const CoreDuelWeightProfile* CoreDuelWeightProfileFind(const char* name, const char* version);
const CoreDuelWeightProfile* CoreDuelWeightProfileDefault(void);
"""


def render_source(profiles) -> str:
    sources = ", ".join(str(path) for path in SOURCE_PATHS)
    records = []
    for profile in profiles:
        fields = "\n".join(
            f"            .{key} = {_c_double(profile.weights[key])}," for key in WEIGHT_KEYS
        )
        records.append(
            "    {\n"
            f"        .schema_version = {profile.schema_version},\n"
            f"        .name = {_c_string(profile.name)},\n"
            f"        .version = {_c_string(profile.version)},\n"
            f"        .status = {_c_string(profile.status)},\n"
            f"        .sha256 = {_c_string(profile.sha256)},\n"
            "        .weights = {\n"
            f"{fields}\n"
            "        },\n"
            "    },"
        )
    return f"""/* Generated by tools/tuning/generate_duel_weight_profiles.py.
 * Sources: {sources}
 * DO NOT EDIT. */
#include "duel_weight_profiles_generated.h"

#include <string.h>

static const CoreDuelWeightProfile CORE_DUEL_WEIGHT_PROFILES[] = {{
{chr(10).join(records)}
}};

size_t CoreDuelWeightProfileCount(void) {{
    return sizeof(CORE_DUEL_WEIGHT_PROFILES) / sizeof(CORE_DUEL_WEIGHT_PROFILES[0]);
}}

const CoreDuelWeightProfile* CoreDuelWeightProfileAt(size_t index) {{
    return index < CoreDuelWeightProfileCount() ? &CORE_DUEL_WEIGHT_PROFILES[index] : NULL;
}}

const CoreDuelWeightProfile* CoreDuelWeightProfileFind(const char* name, const char* version) {{
    if (name == NULL || version == NULL) {{
        return NULL;
    }}
    for (size_t index = 0; index < CoreDuelWeightProfileCount(); ++index) {{
        const CoreDuelWeightProfile* profile = &CORE_DUEL_WEIGHT_PROFILES[index];
        if (strcmp(profile->name, name) == 0 && strcmp(profile->version, version) == 0) {{
            return profile;
        }}
    }}
    return NULL;
}}

const CoreDuelWeightProfile* CoreDuelWeightProfileDefault(void) {{
    for (size_t index = 0; index < CoreDuelWeightProfileCount(); ++index) {{
        if (strcmp(CORE_DUEL_WEIGHT_PROFILES[index].status, "production-default") == 0) {{
            return &CORE_DUEL_WEIGHT_PROFILES[index];
        }}
    }}
    return NULL;
}}
"""


def render_manifest(outputs: dict[Path, str]) -> str:
    entries: list[tuple[Path, bytes]] = [
        (path, (ROOT / path).read_bytes()) for path in SOURCE_PATHS
    ]
    entries.extend((path, outputs[path].encode("utf-8")) for path in (HEADER_PATH, SOURCE_PATH))
    return "".join(
        f"{hashlib.sha256(content).hexdigest()}  {path}\n" for path, content in entries
    )


def generated_outputs() -> dict[Path, str]:
    profiles = validate_profiles(load_profile(ROOT / path) for path in SOURCE_PATHS)
    outputs = {HEADER_PATH: render_header(), SOURCE_PATH: render_source(profiles)}
    outputs[MANIFEST_PATH] = render_manifest(outputs)
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = generated_outputs()
    if args.check:
        stale = [
            path
            for path, expected in outputs.items()
            if not (ROOT / path).is_file() or (ROOT / path).read_text() != expected
        ]
        if stale:
            parser.error("generated duel weight profiles are stale: " + ", ".join(map(str, stale)))
        return 0
    for path, content in outputs.items():
        destination = ROOT / path
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
