/* Generated by tools/tuning/generate_duel_weight_profiles.py.
 * Sources: configs/evaluation_weights/default.json, configs/evaluation_weights/tuned-opponent-pressure.json
 * DO NOT EDIT. */
#include "duel_weight_profiles_generated.h"

#include <string.h>

static const CoreDuelWeightProfile CORE_DUEL_WEIGHT_PROFILES[] = {
    {
        .schema_version = 1,
        .name = "duel-default",
        .version = "1",
        .status = "production-default",
        .sha256 = "a51a2213f403f1e21ccb4eb928927bfac72a11acd7e1d52de2f88ef2277f9629",
        .weights = {
            .terminal_win = 1000000.0,
            .terminal_loss = -1000000.0,
            .base = 500.0,
            .health = 0.7,
            .length = 18.0,
            .reachable_space = 4.0,
            .safe_moves = 35.0,
            .center = 2.0,
            .food = 55.0,
            .low_health_food = 120.0,
            .low_health_threshold = 35.0,
            .hazard_damage = 1.0,
            .hazard = 25.0,
            .length_advantage = 5.0,
            .adjacent_equal_or_longer_penalty = 120.0,
            .adjacent_shorter_bonus = 45.0,
            .opponent_reachable_space = 0.0,
            .territory_delta = 0.0,
            .opponent_safe_moves = 0.0,
            .opponent_low_health_food_denial = 0.0,
        },
    },
    {
        .schema_version = 1,
        .name = "tuned-opponent-pressure",
        .version = "1",
        .status = "candidate",
        .sha256 = "6996443271beb18e835355a72ad02e2ee9d47148a33e14370ce096fc766f1c5d",
        .weights = {
            .terminal_win = 1000000.0,
            .terminal_loss = -1000000.0,
            .base = 500.0,
            .health = 0.7,
            .length = 18.0,
            .reachable_space = 4.0,
            .safe_moves = 35.0,
            .center = 2.0,
            .food = 55.0,
            .low_health_food = 120.0,
            .low_health_threshold = 35.0,
            .hazard_damage = 1.0,
            .hazard = 25.0,
            .length_advantage = 5.0,
            .adjacent_equal_or_longer_penalty = 120.0,
            .adjacent_shorter_bonus = 45.0,
            .opponent_reachable_space = 0.41419471771599625,
            .territory_delta = 1.8353673505986556,
            .opponent_safe_moves = 71.36454529204393,
            .opponent_low_health_food_denial = 0.9747950851938381,
        },
    },
};

size_t CoreDuelWeightProfileCount(void) {
    return sizeof(CORE_DUEL_WEIGHT_PROFILES) / sizeof(CORE_DUEL_WEIGHT_PROFILES[0]);
}

const CoreDuelWeightProfile* CoreDuelWeightProfileAt(size_t index) {
    return index < CoreDuelWeightProfileCount() ? &CORE_DUEL_WEIGHT_PROFILES[index] : NULL;
}

const CoreDuelWeightProfile* CoreDuelWeightProfileFind(const char* name, const char* version) {
    if (name == NULL || version == NULL) {
        return NULL;
    }
    for (size_t index = 0; index < CoreDuelWeightProfileCount(); ++index) {
        const CoreDuelWeightProfile* profile = &CORE_DUEL_WEIGHT_PROFILES[index];
        if (strcmp(profile->name, name) == 0 && strcmp(profile->version, version) == 0) {
            return profile;
        }
    }
    return NULL;
}

const CoreDuelWeightProfile* CoreDuelWeightProfileDefault(void) {
    for (size_t index = 0; index < CoreDuelWeightProfileCount(); ++index) {
        if (strcmp(CORE_DUEL_WEIGHT_PROFILES[index].status, "production-default") == 0) {
            return &CORE_DUEL_WEIGHT_PROFILES[index];
        }
    }
    return NULL;
}
