/* Generated by tools/tuning/generate_duel_weight_profiles.py.
 * Sources: configs/evaluation_weights/default.json, configs/evaluation_weights/tuned-opponent-pressure.json
 * DO NOT EDIT. */
#pragma once

#include <stddef.h>

#include "search_stats.h"

typedef struct {
    int schema_version;
    const char* name;
    const char* version;
    const char* status;
    const char* sha256;
    CoreEvaluationWeights weights;
} CoreDuelWeightProfile;

size_t CoreDuelWeightProfileCount(void);
const CoreDuelWeightProfile* CoreDuelWeightProfileAt(size_t index);
const CoreDuelWeightProfile* CoreDuelWeightProfileFind(const char* name, const char* version);
const CoreDuelWeightProfile* CoreDuelWeightProfileDefault(void);
